FROM debian:jessie

MAINTAINER Alexandre Borgo <alexandre.borgo@free.fr>

RUN apt-get update && apt-get install -y nginx

ADD default.conf /etc/nginx/conf.d/

RUN echo "upstream php-upstream { server php:9000; }" > /etc/nginx/conf.d/upstream.conf

RUN usermod -u 1000 www-data

CMD ["nginx", "-g", "daemon off;"]

EXPOSE 80 443